name: Try Build

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: 'Branch to use'
        required: true
        default: 'master'
        type: choice

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: node --version
      name: Check Node Version
    
    - uses: actions/checkout@v3
      name: Checkout code

    - run: yarn
      name: Install NPM Packages
    
    - run: yarn build
      name: Build Project
      
