name: Try Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:14
    steps:
    - run: node --version
    - name: Check Node Version
    
    - uses: actions/checkout@v3

    - name: Build
      run: |
        yarn
        yarn build
